mauth-proxy/README.md
mauth-proxy/pom.xml
mauth-proxy/src/deploy/deb/control/control
mauth-proxy/src/deploy/deb/control/postinst
mauth-proxy/src/deploy/deb/control/preinst
mauth-proxy/src/deploy/deb/control/prerm
mauth-proxy/src/deploy/deb/upstart/mauth-proxy.conf
mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyConfig.java
mauth-proxy/src/main/resources/reference.conf
mauth-proxy/src/test/resources/application.conf

Generate deb file for installing on Debian OS
@mdrynkorn-mdsol @crudd-mdsol @rmillward-mdsol @eyomi-mdsol

Generate deb file

---

.travis.yml
mauth-proxy/pom.xml
mauth-proxy/src/main/java/com/mdso/util/BuildInfo.java
mauth-proxy/src/main/java/com/mdso/util/BuildInfoService.java
mauth-proxy/src/main/java/com/mdsol/mauth/proxy/MAuthRequestFilter.java
mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyServer.java
mauth-proxy/src/main/resources/build.properties

Add App Status and build info to it
@crudd-mdsol @mdrynkorn-mdsol @eyomi-mdsol @rmillward-mdsol

App Status

---

mauth-proxy/pom.xml
mauth-proxy/src/main/java/com/mdsol/mauth/proxy/MAuthRequestFilter.java
mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyServer.java
mauth-proxy/src/main/java/com/mdsol/util/BuildInfo.java
mauth-proxy/src/main/java/com/mdsol/util/BuildInfoService.java
mauth-proxy/src/main/resources/build.properties

Get git information from git instead of maven
@crudd-mdsol @mdrynkorn-mdsol @eyomi-mdsol @rmillward-mdsol

Improve build info

---

mauth-proxy/src/main/java/com/mdsol/mauth/proxy/MAuthRequestFilter.java

app_status return 200 OK
@rmillward-mdsol @mdrynkorn-mdsol

app_status return 200 OK

---

README.md
mauth-authenticator-apachehttp/README.md
mauth-authenticator-apachehttp/pom.xml
mauth-authenticator-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientPublicKeyProvider.java
mauth-authenticator-apachehttp/src/test/java/com/mdsol/mauth/apache/HttpClientPublicKeyProviderTest.java
mauth-authenticator/pom.xml
mauth-authenticator/src/main/java/com/mdsol/mauth/AuthenticatorConfiguration.java
mauth-authenticator/src/main/resources/reference.conf
mauth-common/pom.xml
mauth-common/src/main/java/com/mdsol/mauth/MAuthConfiguration.java
mauth-proxy/pom.xml
mauth-proxy/src/main/java/com/mdsol/mauth/proxy/MAuthRequestFilter.java
mauth-proxy/src/main/resources/logback.xml
mauth-signer-apachehttp/README.md
mauth-signer-apachehttp/pom.xml
mauth-signer-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientRequestSigner.java
mauth-signer/pom.xml
mauth-signer/src/main/java/com/mdsol/mauth/DefaultSigner.java
mauth-signer/src/main/java/com/mdsol/mauth/SignerConfiguration.java
mauth-signer/src/main/resources/reference.conf
mauth-test-utils/pom.xml
pom.xml

Exclude deb files from shaded jar
@mdsol/team_57

Exclude deb files from shaded jar

---

mauth-authenticator-apachehttp/pom.xml
mauth-authenticator/pom.xml
mauth-common/pom.xml
mauth-proxy/pom.xml
mauth-signer-apachehttp/pom.xml
mauth-signer/pom.xml
mauth-test-utils/pom.xml
pom.xml

release 2016.3.1

---

pom.xml

Use Artv4 as repo

---

build.sbt
modules/mauth-signer-akka-http/README.md
project/BuildSettings.scala
project/Dependencies.scala

fix organisation to push the artifacts to

[MCC-344662] Organisation

---

modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/MAuthRequestSigner.scala
modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/HttpClient.scala

Create RequestSigner to be plain trait and MauthRequestSigner to be class to aid testing

[MCC-352879] RequestSigner trait

---

.travis.yml
project/BuildSettings.scala
project/build.properties
project/plugins.sbt
travis/deploy.sh

Auto release artifacts to artifactory

[MCC-357852] Auto release artifacts to artifactory

---

runMauthProxyServer.bash

Modifying proxy startup script to match new module name

---

project/Dependencies.scala

revert brave library from 5.1.2 back to 4.18.2
@mdsol/yellow-pumas 
@mdsol/green-griffons

MCC-415845: revert brave to 4.18.2

---

project/BuildSettings.scala

Added releaseStepCommandAndRemaining to support cross build release

Add releaseStepCommandAndRemaining

---

.travis.yml
build.sbt
project/BuildSettings.scala
project/build.properties

Fixed release process by not publishing java modules twice

Fixed release process by not publishing java modules twice

---

version.sbt

Increased version

---

modules/mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyServer.java

Changed MaxInitialLength and MaxHeaderLength
@mdsol/green-griffons

Changed MaxInitialLength and MaxHeaderLength

---

version.sbt

0.16 master to develop

---

version.sbt

Master to develop

---

build.sbt
project/BuildSettings.scala
project/plugins.sbt

* Remove unneeded repo resolvers
* Remove mima filter for previous releases

Remove unneeded repos

---

build.sbt

fix version calculation for cross compilation

fix version calculation for cross compilation

---

project/BuildSettings.scala
project/plugins.sbt

remove mimaPreviousArtifacts setting as it's handled by sbt-smartrelease

remove mimaPreviousArtifacts

---

.travis.yml

remove master branch requirement from release stage

fix release stage

---

modules/mauth-signer-akka-http/README.adoc
modules/mauth-signer-akka-http/src/example/resources/application.conf
modules/mauth-signer-apachehttp/README.adoc
modules/mauth-signer-apachehttp/src/example/resources/application.conf

This PR update the readme and sample configuration for signing option.
@mdsol/architecture-enablement  @jatcwang @austek

[MCC-650302] Update readme for signing option

---

CHANGELOG.md
modules/mauth-authenticator-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientPublicKeyProvider.java
project/Dependencies.scala

This PR fixed the issue reported in https://mdsol.slack.com/archives/CCDANR533/p1656530149481259
@mdsol/architecture-enablement @jatcwang @johnduhart

[MCC-942718]Enhance MAuth Authenticator Apachehttp caching

---

project/BuildSettings.scala
project/Dependencies.scala
project/build.properties

upgrade of libs in order to limit number of known vulnerabilities

MCC-980194: upgrade libraries

---

modules/mauth-authenticator-http4s/src/main/scala/com/mdsol/mauth/http4s/MAuthMiddleware.scala
modules/mauth-authenticator-http4s/src/test/scala/com/mdsol/mauth/http4s/MAuthMiddlewareSuite.scala

Update the mAuth http4s middleware to have AuthedRoutes (ContextRoutes) which contains the mAuthHeaderValue and TimeHeaderValue

Tech/mcc 1065900/update middleware to authed routes

---

build.sbt
modules/mauth-authenticator-akka-http/src/main/scala/com/mdsol/mauth/akka/http/MauthPublicKeyProvider.scala
modules/mauth-authenticator-akka-http/src/test/scala/com/mdsol/mauth/akka/http/MauthPublicKeyProviderSpec.scala
modules/mauth-authenticator-http4s/src/main/scala/com/mdsol/mauth/http4s/MauthPublicKeyProvider.scala
modules/mauth-authenticator-http4s/src/test/scala/com/mdsol/mauth/http4s/MauthPublicKeyProviderSuite.scala
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/FakeMAuthServer.java
project/Dependencies.scala

Ensure we dont make additional requests when we get a burst of requests against an empty cache.

Tech: Fix Cache to reduce requests.
