mdsol/mauth-jvm-clients

modules/mauth-authenticator-akka-http/src/main/scala/com/mdsol/mauth/akka/http/MAuthDirectives.scala

Moved rejection type outside of the trait to avoid pattern matching issues.

Moved type definitions outside the main trait.

---

modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/HttpVerbOps.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/http/ImplicitsTest.scala

Fix an issue when using the implicit method "fromSignedRequestToHttpRequest" which is ignoring Https methods other than GET because the method akka.http.scaladsl.model.HttpMethods.getForKeyCaseInsensitive("POST") is returning None. 
This method has been replaced for akka.http.scaladsl.model.HttpMethods.getForKey("POST") which returns the "HttpMethod(POST)" value correctly.

[MCC-403926] Replace getForKeyCaseInsensitive for getForKey

---

modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/Implicits.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/http/ImplicitsTest.scala

Fix POST/PATCH so instead of sending always Content Type "plain/text", enforce that Content-type  been "application/json".

[MCC-403926] Enforce always content type application/json

---

project/Dependencies.scala
version.sbt

As the title says, the goal is to update bouncy castle and sync the snapshot version in develop with the version in master.
Right after this, there will be a PR to merge `develop` into `master` which I expect will do a release of version `1.0.5` into https://repo1.maven.org/maven2/com/mdsol/ for the modules of this repo.
IF someone feels we should really fix `master` with a PR to downgrade the version there to 1.0.2-SNAPSHOT and then publish `1.0.2` that is another way to go.
Here is the relevant Jira ticket https://jira.mdsol.com/browse/MCC-398155

MCC-398155 Update bouncy castle and sync the snapshot version in develop with the version in master.

---

modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/MAuthRequestSigner.scala
modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/HttpVerbOps.scala
modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/Implicits.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/http/ImplicitsTest.scala

The following fixes have been carried out in Scala asynchronous Mauth client:
- Modify HTTP method to make it case-insensitive.
- Add support to customize content-type (apply "text/plain(UTF-8)" by default)
[MCC-414889](https://jira.mdsol.com/browse/MCC-414889)

[MCC-414889] Fix - Add support to customize Content-Type

---

modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/Implicits.scala

Address @red-benabas suggestion to simplify the extractContentTypeFromHeaders method using the map lookup method.

[MCC-414889] Simplify method to extract content-type from headers

---

project/Dependencies.scala

This PR is to increase the version of `scalacache-guava` to avoid binary incompatibilities caused by eviction as latest `platform-common-async` depends on version `0.27.0`.
That leads to issues at runtime like: 
```
java.lang.AbstractMethodError: Method scalacache/guava/GuavaCache.logger()Lscalacache/logging/Logger; is abstract
```

NO-JIRA: scalacache-guava updated

---

modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/http/Implicits.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/MAuthRequestSignerSpec.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/http/ImplicitsTest.scala

Fix - Add support to customize content-type (apply "text/plain(UTF-8)" by default) in mAuthV2
[MCC-530719](https://jira.mdsol.com/browse/MCC-530719)
This is also related to this previous bugfix https://github.com/mdsol/mauth-jvm-clients/pull/71

[MCC-530719] Fix to customize content-type in mAuthV2

---

CHANGELOG.md
modules/mauth-authenticator/src/main/java/com/mdsol/mauth/Authenticator.java
modules/mauth-authenticator/src/main/java/com/mdsol/mauth/RequestAuthenticator.java
modules/mauth-authenticator/src/main/scala/com/mdsol/mauth/scaladsl/RequestAuthenticator.scala
modules/mauth-authenticator/src/test/scala/com/mdsol/mauth/RequestAuthenticatorBaseSpec.scala
modules/mauth-authenticator/src/test/scala/com/mdsol/mauth/RequestAuthenticatorSpec.scala
modules/mauth-authenticator/src/test/scala/com/mdsol/mauth/scaladsl/utils/RequestAuthenticatorSpec.scala
modules/mauth-common/src/main/java/com/mdsol/mauth/MAuthRequest.java
version.sbt

As discussed in this https://docs.google.com/document/d/1UsKJfZeDJb3cbvi0B-z-KMXHrNEGo-GKhXi2k4OnMxU/edit#heading=h.k5ec2aaqcyc0
and same as in ruby https://github.com/mdsol/mauth-client-ruby/pull/38, this PR updates the logic to fall back to V1 authentication when V2 authentication fails.
Please review:
@jatcwang @austek @mcallonalvarez @mdsol/architecture-enablement

[MCC-575954]fall back to V1 when V2 authentication fails

---

build.sbt

To fix the runtime error getting due to common-codec versions, please find the attached screenshot of the error:

Fix of runtime issue,due to multiple version of commons-codec used

---

CHANGELOG.md
modules/mauth-authenticator-akka-http/src/main/scala/com/mdsol/mauth/akka/http/MAuthDirectives.scala
modules/mauth-authenticator-akka-http/src/test/scala/com/mdsol/mauth/akka/http/MAuthDirectivesSpec.scala
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/RequestAuthenticatorBaseSpec.scala
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/RequestAuthenticatorSpec.scala
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/scaladsl/utils/RequestAuthenticatorSpec.scala
modules/mauth-common/src/main/java/com/mdsol/mauth/util/MAuthSignatureHelper.java
modules/mauth-common/src/test/scala/com/mdsol/mauth/MAuthSignatureHelperSpec.scala
modules/mauth-proxy/src/main/java/com/mdsol/mauth/proxy/MAuthHttpRequestSigner.java
modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/MAuthRequestSigner.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/MAuthRequestSignerSpec.scala
modules/mauth-signer-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientRequestSigner.java
modules/mauth-signer-apachehttp/src/test/scala/com/mdsol/mauth/apache/HttpClientRequestSignerSpec.scala
modules/mauth-signer/src/test/scala/com/mdsol/mauth/DefaultSignerSpec.scala
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/FixturesLoader.java

This PR includes the changes:
1. refactor mauth-signer to use the encoded resource path and query parameters for V2(sync up mauth-client-ruby);
2. normalize the resource path;
3. update the tests;
@mdsol/architecture-enablement @austek @jatcwang

[MCC-560247]Refactor mauth-signer with encoded path and query parameters

---

modules/mauth-proxy/src/main/java/com/mdsol/mauth/proxy/MAuthHttpRequestSigner.java
modules/mauth-proxy/src/test/scala/com/mdsol/mauth/proxy/ProxyServerSpec.scala

This PR includes the changes:
1. refactor mauth-proxy to accept POST and PATCH request. (it was failing with 
java.lang.UnsupportedOperationException: direct buffer at com.mdsol.mauth.proxy.MAuthHttpRequestSigner.signRequest(MAuthHttpRequestSigner.java:28)
2. update the tests

[MCC-620147] : mauth-proxy changes to work with POST and PATCH

---

CHANGELOG.md
modules/mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyConfig.java
modules/mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyServer.java
modules/mauth-proxy/src/main/resources/reference.conf
modules/mauth-proxy/src/test/resources/application.conf
modules/mauth-sender-sttp-akka-http/src/test/scala/com/mdsol/mauth/SttpAkkaMAuthRequestSenderSpec.scala
modules/mauth-signer-akka-http/README.adoc
modules/mauth-signer-akka-http/src/main/scala/com/mdsol/mauth/MAuthRequestSigner.scala
modules/mauth-signer-akka-http/src/test/scala/com/mdsol/mauth/MAuthRequestSignerSpec.scala
modules/mauth-signer-apachehttp/README.adoc
modules/mauth-signer-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientRequestSigner.java
modules/mauth-signer-apachehttp/src/test/scala/com/mdsol/mauth/apache/HttpClientRequestSignerSpec.scala
modules/mauth-signer-sttp/src/main/scala/com/mdsol/mauth/MAuthSttpSigner.scala
modules/mauth-signer-sttp/src/test/scala/com/mdsol/mauth/MAuthSttpSignerSpec.scala
modules/mauth-signer/src/main/java/com/mdsol/mauth/DefaultSigner.java
modules/mauth-signer/src/main/java/com/mdsol/mauth/SignerConfiguration.java
modules/mauth-signer/src/main/resources/reference.conf
modules/mauth-signer/src/test/scala/com/mdsol/mauth/DefaultSignerSpec.scala

This PR includes the changes:
1. replace `V2_ONLY_SIGN_REQUESTS` option with `MAUTH_SIGN_VERSIONS` option;
2. change the default to `v2` only for the signing protocol version;
**Notes:**
Since not all apps are updated to the latest, please use v1 when you experience authentication failures.
Ruby: https://github.com/mdsol/mauth-client-ruby/pull/40
Python: https://github.com/mdsol/mauth-client-python/pull/19
@jatcwang @austek @mdsol/architecture-enablement

[MCC-621192]Make the signing protocol versions configurable

---

CHANGELOG.md
modules/mauth-proxy/src/main/java/com/mdsol/mauth/proxy/ProxyConfig.java
modules/mauth-proxy/src/main/resources/reference.conf
modules/mauth-signer-akka-http/README.adoc
modules/mauth-signer-apachehttp/README.adoc
modules/mauth-signer/src/main/java/com/mdsol/mauth/SignerConfiguration.java
modules/mauth-signer/src/test/scala/com/mdsol/mauth/DefaultSignerSpec.scala

This PR changed the default signing versions to 'v1' only. 
**Background**
https://github.com/mdsol/mauth-client-dotnet/pull/63#discussion_r460095452
Out of caution I was going to say we sign with V1 and V2 (or even just V1) by default. I do like the idea of "well behaved" implementations not having to do anything to "turn v2 on" later but I think I'd rather have planned config changes later than risk having some requests failing as inauthentic in production and scrambling to change config. It's likely that we would catch such failures in lower environments and be able to adjust signing config appropriately but it's not certain.
The other language updates: https://github.com/mdsol/mauth-client-python/pull/23
@mdsol/architecture-enablement @austek @jatcwang @cmcinnes-mdsol @jcarres-mdsol

[MCC-650302] Change the default signing versions to v1 only

---

CHANGELOG.md
modules/mauth-authenticator-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientPublicKeyProvider.java
modules/mauth-authenticator-apachehttp/src/test/scala/com/mdsol/mauth/apache/HttpClientPublicKeyProviderSpec.scala
modules/mauth-authenticator-scala/src/main/scala/com/mdsol/mauth/scaladsl/RequestAuthenticator.scala
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/RequestAuthenticatorBaseSpec.scala
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/RequestAuthenticatorSpec.scala
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/scaladsl/utils/RequestAuthenticatorSpec.scala
modules/mauth-authenticator/src/main/java/com/mdsol/mauth/RequestAuthenticator.java
modules/mauth-common/src/main/java/com/mdsol/mauth/MAuthRequest.java
modules/mauth-common/src/main/java/com/mdsol/mauth/util/MAuthSignatureHelper.java
modules/mauth-common/src/test/scala/com/mdsol/mauth/MAuthRequestSpec.scala
modules/mauth-common/src/test/scala/com/mdsol/mauth/MAuthSignatureHelperSpec.scala
modules/mauth-signer-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientRequestSigner.java
modules/mauth-signer-apachehttp/src/test/scala/com/mdsol/mauth/apache/HttpClientRequestSignerSpec.scala
modules/mauth-signer/src/main/java/com/mdsol/mauth/DefaultSigner.java
modules/mauth-signer/src/main/java/com/mdsol/mauth/Signer.java
modules/mauth-signer/src/test/scala/com/mdsol/mauth/DefaultSignerSpec.scala

This PR enhanced mauth-signer and mauth-authenticator to accept the request payload as InputStream.
Note: If payload is stream, 
- mauth-signer generates the signature for v2 only if v2 is required, or the signature for v1 if v1 only is required; 
- mauth-authenticator validates for v2 only if request headers including v2 signature, or validates for v1 if request headers including v1 signature only
@jatcwang @austek @mdsol/architecture-enablement

[MCC-693298]Accept request payload as InputStream for Java

---

.gitmodules
CHANGELOG.md
CONTRIBUTING.adoc
build.sbt
modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/MauthProtocolSuiteSpec.scala
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/ProtocolTestSuiteHelper.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/AuthenticationHeader.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/AuthenticationOnly.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/CaseType.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/SigningAuthentication.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/SigningConfig.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/TestCase.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/model/UnsignedRequest.java

This PR is for supporting [mauth-protocol-test-suite](https://github.com/mdsol/mauth-protocol-test-suite) 
- ProtocolTestSuiteHelper to retrieve the test specs in mauth-protocol-test-suite
- run test specs for verification 
- include submodule mauth-protocol-test-suite in the repo
@mdsol/architecture-enablement @austek @jatcwang

[MCC-750736]support mauth-protocol-test-suite

---

CHANGELOG.md
build.sbt
modules/mauth-authenticator-apachehttp/src/main/java/com/mdsol/mauth/apache/HttpClientPublicKeyProvider.java
modules/mauth-test-utils/src/main/java/com/mdsol/mauth/test/utils/FakeMAuthServer.java
project/Dependencies.scala

- Honor Cache-Control max-age header as cache ttl
- Lazy load LoadingCache object to be able to set the ttl
- Add Caffeine library dependency for more efficient caching ([benchmarks](https://github.com/ben-manes/caffeine/wiki/Benchmarks))
- Add Cache-Control headers in FakeMauthServer response

[MCC-785068] Use Cache Control header as TTL

---

CHANGELOG.md
modules/mauth-authenticator-akka-http/src/test/scala/com/mdsol/mauth/akka/http/MauthPublicKeyProviderSpec.scala
modules/mauth-authenticator-apachehttp/src/test/scala/com/mdsol/mauth/apache/HttpClientPublicKeyProviderSpec.scala
modules/mauth-authenticator/src/main/java/com/mdsol/mauth/AuthenticatorConfiguration.java
modules/mauth-authenticator/src/main/resources/reference.conf

This PR sets the fallback cache TTL to 5 minutes if Cache-Control is missing or malformed, see [MCC-805832)](https://jira.mdsol.com/browse/MCC-805832)
@jatcwang @austek @mdsol/architecture-enablement

[MCC-805832]Set the fallback cache TTL to 5 minutes

---

.travis.yml
CHANGELOG.md
mauth-authenticator-apachehttp/pom.xml
mauth-authenticator/pom.xml
mauth-common/pom.xml
mauth-proxy/pom.xml
mauth-signer-apachehttp/pom.xml
mauth-signer/pom.xml
mauth-test-utils/pom.xml
pom.xml
travis/deploy.sh
travis/settings.xml

This PR includes the updates based on tag 1.0.0
- bump  jackson-databind to 2.13.0;
- bump the version of mauth-clients to 1.0.0.1;
- update the scripts of travis & deploy;
@mdsol/architecture-enablement

[MCC-880023] bump jackson-databind in mauth-proxy 1.0.0

---

modules/mauth-authenticator-akka-http/src/main/scala/com/mdsol/mauth/akka/http/MAuthDirectives.scala
modules/mauth-authenticator-akka-http/src/test/scala/com/mdsol/mauth/akka/http/MAuthDirectivesSpec.scala

According to Polybus API's are to return 401 when mAuth headers are missing. The scala Akka HTTP directive gave a 400 error as it was processing them as a malformed request. I have updated it to use custom error types that extend an authorisation (and thus 401) error.

Tech: Fix Akka MAuth Directive so that missing or malformed headers give a 401 status code

---

modules/mauth-authenticator-http4s/src/main/scala/com/mdsol/mauth/http4s/MAuthMiddleware.scala
modules/mauth-authenticator-http4s/src/test/scala/com/mdsol/mauth/http4s/MAuthMiddlewareSuite.scala
modules/mauth-authenticator-http4s/src/test/scala/com/mdsol/mauth/http4s/MauthPublicKeyProviderSuite.scala
project/BuildSettings.scala
project/build.properties

As reported on [this http4s issue](https://github.com/http4s/http4s/issues/7443), in some conditions, if the request's EntityBody is consumed more than once by the caller, a `BodyAlreadyConsumedError` is raised. In our MAuthMiddleware, this can happen when performing the mAuth authentication on large or slow requests, whereby the request's Stream might be chunked, requiring multiple consumptions and causing intermittent failures.
This PR aims at solving this bug

NOJIRA fix body consumption in http4s

---

project/Dependencies.scala

 tech/no_jira/updateDependencies

---

modules/mauth-authenticator-scala/src/test/scala/com/mdsol/mauth/RequestAuthenticatorSpec.scala
modules/mauth-authenticator/src/main/java/com/mdsol/mauth/RequestAuthenticator.java

The original message `"MAuth request validation failed because of timeout 10 seconds"`
as the request is not exactly "timing out" and does not represent a the definition of a "timeout". 
The correction: `"MAuth request validation failed because request time was older than 10 seconds"`
is truer to the events as the request time is in fact to old.
I found this as my machine's system time was too old and this bad error message sent me and I have heard others down a bad rabbit whole of checking private keys and time wasted debugging mauth.

[NOJIRA] Adjust message when request time is too old

---

build.sbt
project/BuildSettings.scala

After running into some maintenance issues with [clojure-mauth-client](https://github.com/mdsol/clojure-mauth-client), I would like to write a new version that reuses the production-proven Java core here, including the testing utilities. I first looked at adding it as a module here, with @tmilner's help, but we were not able to find a usable Clojure plugin for sbt.
This change simply publishes the mauth-test-utils module as an artifact, so that other JVM-based projects with different build tools can reuse it.
Other alternatives considered:
- Write the Clojure implementation without using mauth-test-utils. This would involve reinventing an excessive number of wheels.
- Migrate this project to gradle or maven, which are generally able to support any JVM language. This may be worth …

Publish mauth-test-utils
